ALTER TABLE "Suggestion"
ADD COLUMN "analysisMode" TEXT NOT NULL DEFAULT 'GENERAL',
ADD COLUMN "output" TEXT;

ALTER TABLE "ScreenContext"
ADD COLUMN "code" TEXT NOT NULL DEFAULT '',
ADD COLUMN "language" TEXT NOT NULL DEFAULT '',
ADD COLUMN "terminalOutput" TEXT NOT NULL DEFAULT '',
ADD COLUMN "errors" TEXT NOT NULL DEFAULT '',
ADD COLUMN "detectedQuestion" TEXT NOT NULL DEFAULT '',
ADD COLUMN "codeDetected" BOOLEAN NOT NULL DEFAULT false;
