ALTER TABLE "Suggestion"
ADD COLUMN "promptDebug" TEXT NOT NULL DEFAULT '';

ALTER TABLE "ScreenContext"
ADD COLUMN "rawOcrText" TEXT NOT NULL DEFAULT '',
ADD COLUMN "ocrConfidence" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "captureStatus" TEXT NOT NULL DEFAULT 'working',
ADD COLUMN "ocrStatus" TEXT NOT NULL DEFAULT 'pending';
